### ISSUE TITLE
Update UG based on Group 1's Peer Review

### ISSUE THREAD

**Issue by RyanCheungJF** [AY2122S2-CS2103T-T09-2/tp#112]
The doc containing feedback can be found [here](https://nusu-my.sharepoint.com/:w:/r/personal/elcdlr_nus_edu_sg/_layouts/15/Doc.aspx?sourcedoc=%7B1652F491-FB3C-4219-B70E-D985A1A4152A%7D&file=10.2%20Grp%202%20peer%20review%20by%20grp%201.docx&action=default&mobileredirect=true).

Highlighted stuff represent things that can be improved.

- [x] Target Audience in front matters (#122)
- [x] Legend on icons and notations (#122)
- [x] Change single line code blocks to Multiple line without side scroll(PDF conversion scroll sideways (#122)
- [x] Ensure TOC link provided after every section for consistency (#114)
- [x] Improve tone to less formal and more personal (#122)
- [x] Improve ambiguity of explanations(i.e. “e.g. 5 will not delete if there are only 4 applicants in the list” -> For this example, it is unclear what 5 represents). (#122)
- [x] Add flag command to table of cmds and usage (#122)
- [x] Layout on PDF conversion (For final submission)

Non Feedback Inputs 

- [x] Include UI and explain different panels (Once UI is fixed in 1.4)
- [x] Include sample outputs from UI (Once UI is fixed in 1.4)

Great consistency and correct

Deadline is 28/3 Monday 12pm for CS2101 UG Consult!
